# Site settings

title: Great New Blog Title
author: 
  name: Gabrielle Florencia
  email: gabrielleflorenciaa@gmail.com
description: Great site about Jekyll on Github Pages

# Build settings

remote_theme: jekyll/minima
